export const Projekts = [
  {
    img: "/images/afropolisred.png",
    title: "Afropolis",
    link: "https://play.google.com/store/apps/details?id=com.afro.afropolis",
    techUsed: ["React Native", "React", "TypeScript", "Animation"],
    about:
      " A social media platform where African creatives can meetand share their work",
  },
  {
    img: "/images/task_manager.png",
    title: "Task Manager",
    link: "https://jimitaskmanager.netlify.app/",
    techUsed: ["NestJS", "React", "redux-toolkit", "framer-motion"],
    about: "A Task Management App",
  },
  {
    img: "/images/large.png",
    title: "i-Simplify",
    link: "https://i-simplify.netlify.app/",
    techUsed: ["Apollo", "GraphQL", "React"],
    about: "An e-learning platform (Yet to Connect to Backend)",
  },
  {
    img: "/images/wotsapp.jpg",
    title: "Ghimmy's Blog",
    link: "https://ghimmysblog.netlify.app",
    techUsed: ["firebase", "react"],
    about: "My personal blog",
  },

  {
    img: "/images/futball.jpg",
    title: "Futboll",
    link: "https://futboll.netlify.app",
    techUsed: ["MongoDB", "React", "redux"],
    about: "Check for football Live update",
  },
  {
    img: "/images/wotsapp.jpg",
    title: "WhatsApp",
    link: "https://whatsapp-clone-64096.web.app/",
    techUsed: ["firebase", "react"],
    about: " A whatsapp clone",
  },
  {
    img: "/images/shop.jpg",
    title: "SHOP (Mobile)",
    link: "https://expo.io/@ghimmy/projects/shopApp",
    techUsed: ["firebase", "react native"],
    about: "A React Native e-commerce store",
  },
  {
    img: "/images/covid.jpg",
    title: "Covid19-tracker",
    link: "https://5f7ce00df0925000dd584a28--covld19tracker.netlify.app/",
    techUsed: ["react", "covidApi"],
    about: "A cobod-19 tracker",
  },
  {
    img: "/images/amazon.jpg",
    title: "Amazon Clone",
    link: "https://601cdd3583c3146a5e1bdaf1--amazorne.netlify.app/",
    techUsed: ["node", "express", "MongoDb"],
    about: "An Amazon clone",
  },
  {
    img: "/images/recipe.jpg",
    title: "Recipe App (Mobile)",
    link: "https://expo.io/@ghimmy/projects/rnativetest",
    techUsed: ["react native"],
    about: " A recipe app",
  },
  {
    img: "/images/expense.jpg",
    title: "Expensify",
    link: "https://expensify-41cde.web.app/",
    techUsed: ["React"],
    about: "Monitor your daily expenses",
  },
  {
    img: "/images/portf.jpg",
    title: "Portfolio",
    link: "https://ifeoluwadeleke.netlify.app",
    techUsed: ["node", "react"],
    about: "My portfolio website",
  },
];
